### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by sinus-x** [nerik/osm-poetry#8]
Hi,
would it be possible to add support for more languages, based on targeted country? When you target non-english speaking location, the immersion is broken because of languages being mixed.

I'd be happy to provide czech strings if it was implemented.

**Comment by nerik** [comment]
Hi there,

That's a great idea. We've just added support for multiple languages and Spanish and French versions. Just copy the `lines.en.js` file to a `lines.cs.js` file and start translating :) 
I can help later with adding Czech to the language selector.

Mockrát děkuji!
